spring.application.name=LMS
spring.data.mongodb.host=localhost
spring.data.mongodb.database=LMS
spring.data.mongodb.port=27017
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=94saleem@gmail.com
spring.mail.password=nmgj bemy xnhr grgs

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB